/**
 * Generates supabase/seed.sql from the canonical TypeScript seed data, so the
 * database seed can never drift from what the magazine renders.
 *
 * Run:  node --experimental-strip-types scripts/gen-seed.ts
 * (or:  npm run gen:seed)
 *
 * IDs are deterministic UUIDv5 values derived from natural keys (slugs), so the
 * seed is fully idempotent — re-running it is a no-op via `on conflict do nothing`.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { DESTINATIONS } from "../src/lib/data/destinations.ts";
import { CATEGORIES } from "../src/lib/data/categories.ts";
import { HOSTS } from "../src/lib/data/hosts.ts";
import { EXPERIENCES } from "../src/lib/data/experiences.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---- deterministic UUIDv5 --------------------------------------------------
const NAMESPACE = "1b671a64-40d5-491e-99b0-da01ff1f3341";
function uuidToBytes(u: string): number[] {
  return u.replace(/-/g, "").match(/.{2}/g)!.map((b) => parseInt(b, 16));
}
function bytesToUuid(b: Uint8Array): string {
  const h = Array.from(b, (x) => x.toString(16).padStart(2, "0"));
  return `${h.slice(0, 4).join("")}-${h.slice(4, 6).join("")}-${h.slice(6, 8).join("")}-${h.slice(8, 10).join("")}-${h.slice(10, 16).join("")}`;
}
function uuid5(name: string): string {
  const hash = createHash("sha1")
    .update(Buffer.concat([Buffer.from(uuidToBytes(NAMESPACE)), Buffer.from(name, "utf8")]))
    .digest();
  const b = hash.subarray(0, 16);
  b[6] = (b[6] & 0x0f) | 0x50; // version 5
  b[8] = (b[8] & 0x3f) | 0x80; // variant
  return bytesToUuid(b);
}
const id = (kind: string, key: string) => uuid5(`${kind}:${key}`);

// ---- SQL literal helpers ---------------------------------------------------
const esc = (s: string) => s.replace(/'/g, "''");
const S = (v: unknown) => (v == null ? "null" : `'${esc(String(v))}'`);
const N = (v: number) => String(Math.round(v));
const B = (v: boolean) => (v ? "true" : "false");
const arr = (a: string[]) => (a.length ? `array[${a.map(S).join(", ")}]::text[]` : "'{}'::text[]");
const jsonb = (o: unknown) => `'${esc(JSON.stringify(o))}'::jsonb`;

// Placeholder media path (swap for a real CDN URL when you have photography).
const img = (seed: string, w: number, h: number) =>
  `/api/placeholder?seed=pb-${encodeURIComponent(seed)}&w=${w}&h=${h}`;

const out: string[] = [];
const w = (line = "") => out.push(line);

w("-- Paradise Beyond — catalogue seed (generated by scripts/gen-seed.ts)");
w("-- Idempotent: safe to run repeatedly. Run AFTER 0001_schema.sql + 0002_rls.sql.");
w("-- Regenerate with: npm run gen:seed");
w("");
w("begin;");
w("");

// Commission rule
w("-- Commission (configurable; snapshotted onto each booking at purchase)");
w(
  `insert into commission_rules (id, name, rate_bps, destination_id, active) values ` +
    `(${S(id("commission", "default"))}, 'Global default', 1500, null, true) on conflict (id) do nothing;`,
);
w("");

// Destinations
w("-- Destinations");
for (const d of DESTINATIONS) {
  w(
    `insert into destinations (id, slug, name, country, region, summary, description, image_url, featured) values (` +
      `${S(id("destination", d.slug))}, ${S(d.slug)}, ${S(d.name)}, ${S(d.country)}, ${S(d.region ?? null)}, ${S(d.summary)}, ${S(d.description)}, ${S(img(d.imageSeed, 2000, 1200))}, ${B(d.featured)}) on conflict (id) do nothing;`,
  );
}
w("");

// Categories
w("-- Categories");
CATEGORIES.forEach((c, i) => {
  w(
    `insert into categories (id, slug, name, display_label, tagline, description, sort_order) values (` +
      `${S(id("category", c.slug))}, ${S(c.slug)}, ${S(c.name)}, ${S(c.displayLabel ?? null)}, ${S(c.tagline)}, ${S(c.description)}, ${N(i)}) on conflict (id) do nothing;`,
  );
});
w("");

// Hosts (owner_id linked later by scripts/bootstrap-auth.mjs)
w("-- Hosts (owner_id is linked to an auth profile by bootstrap-auth.mjs)");
for (const h of HOSTS) {
  w(
    `insert into hosts (id, owner_id, slug, name, headline, bio, qualifications, specialisms, socials, image_url, verified) values (` +
      `${S(id("host", h.slug))}, null, ${S(h.slug)}, ${S(h.name)}, ${S(h.headline)}, ${S(h.bio)}, ${arr(h.qualifications)}, ${arr(h.specialisms)}, ${jsonb(h.socials)}, ${S(img(h.imageSeed, 600, 720))}, ${B(h.verified)}) on conflict (id) do nothing;`,
  );
}
w("");

// Experiences and all children
for (const e of EXPERIENCES) {
  const expId = id("experience", e.slug);
  const propId = id("property", e.slug);
  w(`-- ===== ${e.name} =====`);

  // Property (accommodation)
  w(
    `insert into properties (id, destination_id, name, description, location_label, verified) values (` +
      `${S(propId)}, ${S(id("destination", e.destinationSlug))}, ${S(e.stay.property)}, ${S(e.stay.description)}, ${S(e.location)}, ${B(e.verified)}) on conflict (id) do nothing;`,
  );

  // Experience (with the full editorial read model in `content`)
  w(
    `insert into experiences (id, slug, name, strapline, status, duration, destination_id, property_id, location_label, currency, price_from_minor, max_group_size, verified, featured, hero_image_url, story, for_you_if, content) values (` +
      `${S(expId)}, ${S(e.slug)}, ${S(e.name)}, ${S(e.strapline)}, 'published', ${S(String(e.duration))}, ${S(id("destination", e.destinationSlug))}, ${S(propId)}, ${S(e.location)}, ${S(e.currency)}, ${N(e.priceFromMinor)}, ${N(e.maxGroupSize)}, ${B(e.verified)}, ${B(e.featured)}, ${S(img(e.heroImageSeed, 2000, 1200))}, ${jsonb(e.story)}, ${jsonb(e.forYouIf)}, ${jsonb(e)}) on conflict (id) do nothing;`,
  );

  // Host links
  for (const hs of e.hostSlugs) {
    w(
      `insert into experience_hosts (experience_id, host_id) values (${S(expId)}, ${S(id("host", hs))}) on conflict do nothing;`,
    );
  }
  // Category links
  for (const cs of e.categorySlugs) {
    w(
      `insert into experience_categories (experience_id, category_id) values (${S(expId)}, ${S(id("category", cs))}) on conflict do nothing;`,
    );
  }

  // Inclusions / exclusions
  e.inclusions.forEach((label, i) => {
    w(
      `insert into experience_inclusions (id, experience_id, kind, label, sort_order) values (${S(id("inc", `${e.slug}:in:${i}`))}, ${S(expId)}, 'included', ${S(label)}, ${N(i)}) on conflict (id) do nothing;`,
    );
  });
  e.exclusions.forEach((label, i) => {
    w(
      `insert into experience_inclusions (id, experience_id, kind, label, sort_order) values (${S(id("inc", `${e.slug}:ex:${i}`))}, ${S(expId)}, 'excluded', ${S(label)}, ${N(i)}) on conflict (id) do nothing;`,
    );
  });

  // Media (hero + gallery + stay images)
  [e.heroImageSeed, ...e.gallerySeeds, ...e.stay.imageSeeds].forEach((seed, i) => {
    w(
      `insert into experience_media (id, experience_id, url, alt, kind, sort_order) values (${S(id("media", `${e.slug}:${i}`))}, ${S(expId)}, ${S(img(seed, 1200, 800))}, ${S(e.name)}, 'image', ${N(i)}) on conflict (id) do nothing;`,
    );
  });

  // Room types
  e.stay.roomTypes.forEach((r, i) => {
    w(
      `insert into room_types (id, experience_id, code, name, description, occupancy, price_delta_minor, sort_order) values (${S(id("room", `${e.slug}:${r.id}`))}, ${S(expId)}, ${S(r.id)}, ${S(r.name)}, ${S(r.description)}, ${S(r.occupancy)}, ${N(r.priceDeltaMinor)}, ${N(i)}) on conflict (id) do nothing;`,
    );
  });

  // Itinerary
  for (const day of e.itinerary) {
    const dayId = id("day", `${e.slug}:${day.day}`);
    w(
      `insert into itinerary_days (id, experience_id, day_number, title, summary) values (${S(dayId)}, ${S(expId)}, ${N(day.day)}, ${S(day.title)}, ${S(day.summary ?? null)}) on conflict (id) do nothing;`,
    );
    day.items.forEach((it, i) => {
      w(
        `insert into itinerary_items (id, day_id, title, time_label, sort_order) values (${S(id("item", `${e.slug}:${day.day}:${i}`))}, ${S(dayId)}, ${S(it.title)}, ${S(it.time ?? null)}, ${N(i)}) on conflict (id) do nothing;`,
      );
    });
  }

  // Departures + per-room inventory
  for (const dep of e.departures) {
    const depId = id("departure", dep.id);
    w(
      `insert into departures (id, experience_id, code, start_date, end_date, currency, price_from_minor, deposit_minor, balance_due_days, capacity, spaces_remaining, status) values (${S(depId)}, ${S(expId)}, ${S(dep.id)}, ${S(dep.startDate)}, ${S(dep.endDate)}, ${S(dep.currency)}, ${N(dep.priceFromMinor)}, ${N(dep.depositMinor)}, ${N(dep.balanceDueDays)}, ${N(dep.capacity)}, ${N(dep.spacesRemaining)}, ${S(dep.status)}) on conflict (id) do nothing;`,
    );
    e.stay.roomTypes.forEach((r) => {
      w(
        `insert into departure_room_inventory (id, departure_id, room_type_id, capacity, spaces_remaining) values (${S(id("inv", `${dep.id}:${r.id}`))}, ${S(depId)}, ${S(id("room", `${e.slug}:${r.id}`))}, ${N(dep.capacity)}, ${N(dep.spacesRemaining)}) on conflict (id) do nothing;`,
      );
    });
  }
  w("");
}

w("commit;");
w("");

const target = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(target, out.join("\n"));
console.log(`Wrote ${target} (${out.length} lines)`);
